# Generated by Django 5.0 on 2023-12-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qr_model_auth",
            name="dob",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
