# Generated by Django 5.0 on 2023-12-27 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr_app", "0002_alter_qr_model_auth_dob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="qr_model_auth",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ok",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
